
// This file has been generated by the GUI designer. Do not modify.
namespace casterlay
{
	public partial class Overlay
	{
		private global::Gtk.Image image3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget casterlay.Overlay
			global::Stetic.BinContainer.Attach(this);
			this.Name = "casterlay.Overlay";
			// Container child casterlay.Overlay.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image();
			this.image3.Name = "image3";
			this.Add(this.image3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
